### ISSUE TITLE
 Failed to load the intentions package

### ISSUE THREAD

**Issue by Diveshparshionikar** [steelbrain/intentions#104]
after the new update, I have an issue 
I delete the package and reinstalled but didn't work.

**Comment by ttxtea** [comment]
Same issue here. It states:

~~~
function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var e,t=require("atom").Disposable,n=require("assert"),i=(e=require("disposable-event"))&&e.__esModule?e.default:e;function s(e,t,n,i){Object.defineProperty(e,t,{get:n,set:i,enumerable:!0,configurable:!0})}s(module.exports,"consumeHighlightIntentions",(()=>Re)),s(module.exports,"activate",(()=>je)),s(module.exports,"deactivate",(()=>Fe)),s(module.exports,"consumeListIntentions",(()=>Ve));var o={};Object.defineProperty(o,"__esModule",{value:!0}),o.CompositeDisposable=o.Disposable=o.Emitter=void 0;var r={};Object.defineProperty(r,"__esModule",{value:!0}),r.default=void 0;var l=function(){function e(e,t){for(var n=0;n<t.length;n++){var i=t[n];i.enumerable=i.enumerable||!1,i.configurable=!0,"value"in i&&(i.writable=!0),Object.defineProperty(e,i.key,i)}}return function(t,n,i){return n&&e(t.prototype,n),i&&e(t
SyntaxError: Unexpected token .
    at new Script (vm.js:83:7)
    at NativeCompileCache.runInThisContext (/usr/share/atom/resources/app/static/<embedded>:11:146391)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147275)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:696928)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3578827)
    at /usr/share/atom/resources/app/static/<embedded>:11:3565367
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3564167)
    at Package.load (/usr/share/atom/resources/app/static/<embedded>:11:3564940)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/static/<embedded>:11:382096)
    at /usr/share/atom/resources/app/static/<embedded>:11:380519
    at Config.transact (/usr/share/atom/resources/app/static/<embedded>:11:332489)
    at PackageManager.loadPackages (/usr/share/atom/resources/app/static/<embedded>:11:380457)
    at /usr/share/atom/resources/app/static/<embedded>:1:717515
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app/static/<embedded>:1:719554)
~~~

**Comment by aminya** [comment]
This package does not work on older Atoms. You should install the latest version of Atom from: https://atom.io/

**Comment by VinuRajaKumar** [comment]
This issue persists in version 1.53.0 too.

**Comment by ttxtea** [comment]
Hi,
for me it works now, that I have upgraded to

~~~
Atom    : 1.57.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
~~~

**Comment by mikezentz** [comment]
I'm getting the same error:
Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

**Comment by aminya** [comment]
@mikezentz your Atom is old.

**Comment by steelbrain** [comment]
@aminya Any ideas how people are able to install this package on older versions of Atom even tho we specify the `atom` version in `engines`? https://github.com/steelbrain/intentions/blob/c6f9507baef775ac932e21bb77b466d1507d9c07/package.json#L11

**Comment by aminya** [comment]
I released 2.1.0 without the Atom engine specified. Should we unpublish that?

I see the bright side of this. It makes people upgrade their Atom version, which is very important.

**Comment by steelbrain** [comment]
@aminya While I do think it's nice to have people upgrade their Atom version, but "Failed to load package" may not be a good experience in doing so. I think it's best if we unpublish that version, and let people enjoy the latest version after their Atom is up to date. Thoughts?

**Comment by aminya** [comment]
Yes, we can unpublish that. We need to update the changelog after doing so.

**Comment by WalnussPower** [comment]
You should also be aware, that not everybody might want to add Atom's apt repository just to use your extension. For example, the most current version of Atom provided in Pop!_OS's default repositories is Atom 1.54.0.

**Comment by aminya** [comment]
Installing Atom through https://atom.io/ is the only official way supported by Atom itself and us.

https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md

**Comment by steelbrain** [comment]
I have unpublished intentions v2.1.0 from the repository, so people stuck on older Atoms should continue to get a working experience. I would strongly recommend everyone to upgrade their Atom version, and to use a source for doing so that updates it frequently as @aminya recommended.

Thanks everyone for their comments!
