### ISSUE TITLE
Uncaught Error: Cannot find module 'sb-event-kit'

### ISSUE THREAD

**Issue by juanHuizar** [steelbrain/intentions#62]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.1 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [intentions](https://github.com/steelbrain/intentions) package 1.1.2

### Stack Trace

Uncaught Error: Cannot find module 'sb-event-kit'

```
At module.js:457

Error: Cannot find module 'sb-event-kit'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.1/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.1/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.1/resources/app/src/native-compile-cache.js:66:1)
    at /packages/intentions/node_modules/disposable-event/lib/index.js:3:19)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.1/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.1/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.1/resources/app/src/native-compile-cache.js:66:1)
    at /packages/linter-ui-default/lib/editor/index.js:3:35)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.1/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.1/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.1/resources/app/src/native-compile-cache.js:66:1)
    at /packages/linter-ui-default/lib/editors.js:3:43)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.1/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.17.1/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.1/resources/app/src/native-compile-cache.js:66:1)
    at LinterUI.observeShowDecorations (/packages/linter-ui-default/lib/main.js:51:19)
```

### Commands

```
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.6.3 
angularjs 0.4.0 
angularjs-helper 0.10.2 
atom-beautify 0.29.24 
atom-material-syntax 1.0.6 
atom-typescript 11.0.3 
busy-signal 1.4.1 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.6.0 
```

**Comment by steelbrain** [comment]
Sounds like an APM bug.

Can you uninstall and reinstall the package?
