### ISSUE TITLE
Failed to load the intentions package

### ISSUE THREAD

**Issue by qilovehua** [steelbrain/intentions#64]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [intentions](https://github.com/steelbrain/intentions) package 1.1.2

### Stack Trace

Failed to load the intentions package

```
At Cannot find module 'sb-event-kit'

Error: Cannot find module 'sb-event-kit'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:1)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/intentions/lib/main.js:13:19)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/intentions/lib/index.js:3:34)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:158:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:144:1)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:562:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:476:1
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:321:1)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:470:1)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.26 
javascript-snippets 1.2.1 
react-snippets 0.7.4 
autocomplete-paths 1.0.5 
busy-signal 1.4.3 
emmet 2.4.3 
fast-eslint 3.13.0 
git-blame 1.1.1 
hyperclick 0.0.40 
intentions 1.1.2 
js-hyperclick 1.11.0 
last-cursor-position 0.9.2 
linter 2.1.4 
linter-ui-default 1.6.0 
minimap 4.28.2 
platformio-ide-terminal 2.5.1 
terminal-plus 0.14.5 
```

**Comment by steelbrain** [comment]
Looks like an APM install issue

```
apm uninstall intentions
apm install intentions
```

**Comment by qilovehua** [comment]
thanks

**Comment by metakermit** [comment]
Experienced this with busy-signal, linter, linter-ui-default too. It was after I've restored my dotfiles after an OS reinstall.

**Comment by ghost** [comment]
Got similar behaviour after upgrade intentions to version 2.1.0 
Remove and reinstall within the atom settings interface did not help

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.2
**Thrown From**: [intentions](https://github.com/steelbrain/intentions) package 2.1.0


### Stack Trace

Failed to load the intentions package

```
At Unexpected token .

/home/hareldvd/.atom/packages/intentions/dist/index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var e,t=require("atom").Disposable,n=require("assert"),i=(e=require("disposable-event"))&&e.__esModule?e.default:e;function s(e,t,n,i){Object.defineProperty(e,t,{get:n,set:i,enumerable:!0,configurable:!0})}s(module.exports,"consumeHighlightIntentions",(()=>Re)),s(module.exports,"activate",(()=>je)),s(module.exports,"deactivate",(()=>Fe)),s(module.exports,"consumeListIntentions",(()=>Ve));var o={};Object.defineProperty(o,"__esModule",{value:!0}),o.CompositeDisposable=o.Disposable=o.Emitter=void 0;var r={};Object.defineProperty(r,"__esModule",{value:!0}),r.default=void 0;var l=function(){function e(e,t){for(var n=0;n<t.length;n++){var i=t[n];i.enumerable=i.enumerable||!1,i.configurable=!0,"value"in i&&(i.writable=!0),Object.defineProperty(e,i.key,i)}}return function(t,n,i){return n&&e(t.prototype,n),i

SyntaxError: Unexpected token .
    at new Script (vm.js:83:7)
    at NativeCompileCache.runInThisContext (/usr/share/atom/resources/app/static/<embedded>:11:146391)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147275)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:695477)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3196655)
    at /usr/share/atom/resources/app/static/<embedded>:11:3183195
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3181995)
    at Package.load (/usr/share/atom/resources/app/static/<embedded>:11:3182768)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/static/<embedded>:11:381794)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/static/<embedded>:11:380522)
    at PackageManager.atom.packages.loadPackage (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:527:32)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:383094)
    at /usr/share/atom/resources/app/static/<embedded>:11:915835
    at r (/usr/share/atom/resources/app/static/<embedded>:11:910441)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1088976)
    at /usr/share/atom/resources/app/static/<embedded>:14:1089064
    at Socket.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:1087732)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-material-ui 2.1.3 
atom-typescript 14.3.1 
auto-highlight 0.14.0 
busy-signal 2.0.1 
compare-files 0.8.1 
cursor-history 0.14.0 
goto-definition 1.3.4 
highlight-column 0.5.4 
ide-html 0.7.0 
ide-php 0.7.18 
intentions 2.1.0 
js-refactor 0.8.1 
language-pgsql 0.2.3 
linter 3.3.1 
linter-eslint 8.6.6 
linter-ui-default 3.3.1 
local-history 4.3.1 
plsql-linter 2.3.2 
pretty-json 2.1.2 
refactor 0.11.5 
scroll-marker 0.3.5 
Sublime-Style-Column-Selection 1.7.5 
todo-show 2.3.2 
tool-bar 1.4.4 
tool-bar-almighty 0.9.0 
```

**Comment by ameenross** [comment]
Same here

**Comment by scottstensland** [comment]
since this ticket was closed I cut a new issue https://github.com/steelbrain/intentions/issues/91

**Comment by igorpupkinable** [comment]
> apm install intentions

Uninstall/install did not help on Atom v1.54.0 x64.

**Comment by aminya** [comment]
@igorpupkinable Update your Atom to the latest version:
https://atom.io/

**Comment by mdurchholz** [comment]
> @igorpupkinable Update your Atom to the latest version:
> https://atom.io/

Upgrading atom to 1.57.0 did the trick for me. It eventually had me rebuild some packages but we are all ironed out now. Thanks!
